version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-github-actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      security-updates-cargo-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
      version-updates-cargo-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
